#!/bin/bash

if [ $# -eq 3 ]
then
	interface=$2
        interfacemon="${interface}"
	essid=$3


	ifconfig $interface down
	nmcli radio wifi off
	dhclient -r $interface &> /dev/null # release ip

	if [ "$1" = "reset" ]; then
		echo 'Resetting MAC address...'
		echo
		macchanger -p $interface

	elif [ "$1" = "random" ]; then
		echo 'Randomising MAC address...'
		macchanger -r $interface

	else
		echo 'Changing MAC address to $1'
		macchanger -m $1 $interface # change current device mac to input mac

	fi
	
	ifconfig $interface up
	nmcli radio wifi on
	nmcli device wifi connect $essid
	dhclient -v $interface &> /dev/null # get a new ip

else

	echo ""
	echo "Incorrect number of arguments!"
	echo ""
	echo "Useage:"
	echo "$0 {mac address} {interface}"
	echo ""

fi
