#!/bin/bash

curdir=$(pwd)
logfile=installlog.txt

echo "Thanks for using wifiditto! Today's installation log file will be in $curdir/installlog.txt!"

echo "`date` - updating dnf..." | tee -a $logfile
sudo dnf update | tee -a $logfile

echo "`date` - installing dependencies..." | tee -a $logfile
sudo dnf install -y aircrack-ng python3 git macchanger dnsmasq gtk3-devel gcc gcc-c++ kernel-devel pkg-config make hostapd qrencode-devel libpng-devel | tee -a $logfile

echo "`date` - cloning git repos..."
git clone https://github.com/lakinduakash/linux-wifi-hotspot | tee -a $logfile

echo "`date` - installing git repos..."
cd linux-wifi-hotspot && make && sudo make install

echo "`date` - installing WifiDitto..."
sudo cp -r $curdir/wifiditto $curdir/harvested $curdir/modules /bin

echo "`date` - Finish. You can delete the install script if you want ;)" >> $logfile

echo "Done!"
