#!/bin/bash

curdir=$(pwd)
logfile=installlog.txt

echo "Thanks for using wifiditto! Today's installation log file will be in $curdir/installlog.txt!"

echo "`date` - updating apt-get..." | tee -a $logfile
sudo apt update | tee -a $logfile

echo "`date` - installing dependencies..." | tee -a $logfile
sudo apt install -y aircrack-ng python3 git macchanger dnsmasq libgtk-3-dev build-essential gcc g++ pkg-config make hostapd libqrencode-dev libpng-dev | tee -a $logfile

echo "`date` - cloning git repos..."
git clone https://github.com/lakinduakash/linux-wifi-hotspot | tee -a $logfile

echo "`date` - installing git repos..."
cd linux-wifi-hotspot && make && sudo make install

echo "`date` - Finish. You can delete the install script if you want ;)" >> $logfile

echo "Done!"
